spring:
  application:
    name: blog-app
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  graphql:
    graphiql:
      enabled: false
    schema:
      printer:
        enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080

jwt:
  secret: kydcrGu6FakeXO3H2NVYtKR6z/f78GDdGSdcCkqomJo=
  expiration: 86400000

cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:4200
    - http://localhost:8081

logging:
  level:
    com.ally.blogapp: INFO
